import React from "react";

const DesignerAgentTechDebtMapper = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Tech Debt Mapper</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Tech Debt Mapper</strong> agent scores and tracks
              technical debt across your repository to pinpoint code
              maintainability bottlenecks.
            </p>
            <div>
              <img
                alt="Tech Debt Mapper"
                src="/assets/images/think-agent/tech-debt-mapper-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Flexible Assessment Scoping:</strong>
                  <span>
                    Audits targeted source files across your directory tree,
                    with all codebase components pre-selected by default for a
                    complete health baseline.
                  </span>
                </li>
                <li>
                  <strong>Plan Verification:</strong>
                  <span>
                    Generates a quick assessment layout mapping out the targeted
                    directories for your confirmation before starting the deep
                    code analysis.
                  </span>
                </li>
                <li>
                  <strong>Three-Dimensional Code Scoring:</strong>
                  <span>
                    Evaluates each file against critical structural metrics,
                    computing specific scores for cyclomatic complexity, code
                    duplication, and architectural coupling.
                  </span>
                </li>
                <li>
                  <strong>Hotspot Ranking &amp; Trends:</strong>
                  <span>
                    Highlights the most critical areas needing refactoring
                    through ranked priority lists and provides a run-over-run
                    trend analysis to monitor changes over time.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Define Your Code Assessment Scope</h4>
              <p>
                Review your repository directory structure. Keep all source
                files selected to run a project-wide debt audit, or adjust the
                checkboxes to target newly refactored modules or legacy
                components.
              </p>
              <div>
                <img
                  alt="Tech Debt Mapper"
                  src="/assets/images/think-agent/tech-debt-mapper-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Confirm the Assessment Plan</h4>
              <p>
                Examine the structural plan generated by the agent. This step
                outlines the code boundaries and metrics that will be
                calculated. Click Run Scan to launch the codebase assessment.
              </p>
              <div>
                <img
                  alt="Tech Debt Mapper"
                  src="/assets/images/think-agent/tech-debt-mapper-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Structural Analysis Engine</h4>
              <p>
                Allow the agent to parse your files. The engine runs through the
                code paths, counting logic branches for complexity, scanning for
                duplicated blocks, and measuring dependencies to calculate
                coupling scores.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Analyze Hotspots and Maintainability Trends</h4>
              <p>Open the final telemetry dashboard to review your results:</p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Ranked Hotspots:</strong> Focus on the highest-ranked
                  files first; these represent the most complex or tightly
                  coupled code sections requiring immediate refactoring.
                </li>
                <li>
                  <strong>Run-over-Run Trend:</strong> Use the historical
                  tracking view to determine if your technical debt is
                  decreasing over recent development sprints or if new code
                  updates are introducing architectural complexity.
                </li>
              </ul>
              <div>
                <img
                  alt="Tech Debt Mapper"
                  src="/assets/images/think-agent/tech-debt-mapper-4.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentTechDebtMapper;
