import React from "react";

const DesignerAgentComplianceFrameworkMapper = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Compliance Framework Mapper</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Compliance Framework Mapper</strong> agent maps your
              operational evidence documents directly onto regulatory compliance
              frameworks to evaluate audit readiness and isolate coverage gaps.
            </p>
            <div>
              <img
                alt="Compliance Framework Mapper"
                src="/assets/images/think-agent/compliance-framework-mapper-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Framework Alignment:</strong>
                  <span>
                    Cross-references internal documentation against standard
                    regulatory compliance frameworks and control points.
                  </span>
                </li>
                <li>
                  <strong>Dual-Input Selection:</strong>
                  <span>
                    Targets your chosen compliance framework alongside specific
                    evidence files, pre-selecting all workspace documentation by
                    default for complete discovery.
                  </span>
                </li>
                <li>
                  <strong>Automated Control Mapping:</strong>
                  <span>
                    Evaluates every designated document against the granular
                    control requirements of the framework to trace compliant
                    paths.
                  </span>
                </li>
                <li>
                  <strong>Coverage &amp; Gap Analytics:</strong>
                  <span>
                    Calculates an overall framework readiness percentage and
                    generates an explicit gap report detailing which controls
                    lack sufficient documentation.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Select Framework and Evidence Docs</h4>
              <p>
                Choose your target compliance framework from the configuration
                menu. Review your workspace files and select the evidence
                folders, policies, or technical logs you want to assess, leaving
                all selected by default for maximum coverage.
              </p>
              <div>
                <img
                  alt="Compliance Framework Mapper"
                  src="/assets/images/think-agent/compliance-framework-mapper-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Approve the Mapping Plan</h4>
              <p>
                Review the preliminary outline generated by the agent, which
                maps out the targeted document boundaries and selected
                compliance modules. Confirm the plan to launch the parsing
                routine.
              </p>
              <div>
                <img
                  alt="Compliance Framework Mapper"
                  src="/assets/images/think-agent/compliance-framework-mapper-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Compliance Audit Trace</h4>
              <p>
                Allow the agent to process your project assets. The engine maps
                each document text string against specific regulatory controls,
                verifying audit viability and highlighting unsupported
                requirements.
              </p>
              <div>
                <img
                  alt="Compliance Framework Mapper"
                  src="/assets/images/think-agent/compliance-framework-mapper-4.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 4: Evaluate Coverage and Address Gaps</h4>
              <p>
                Open the finalized compliance dashboard to analyze your audit
                stance:
              </p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Coverage Percentage:</strong> Review your high-level
                  readiness score to understand how close your organization is
                  to total framework compliance.
                </li>
                <li>
                  <strong>Gap Report:</strong> Isolate the specific regulatory
                  controls flagged as unmapped or under-documented, allowing you
                  to proactively draft missing policies before formal audits.
                </li>
              </ul>
              <div>
                <img
                  alt="Compliance Framework Mapper"
                  src="/assets/images/think-agent/compliance-framework-mapper-5.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentComplianceFrameworkMapper;
