import React from 'react';

const DesignerAgentSchemaDocGenerator = () => {
  return (
    <div className="doc-page-content">
      <main className="cd-main-content" id="cd-main">
<h1 className="cd-page-title" id="cdHomeTitle">
                    Schema Doc Generator
                </h1>
<section className="cd-overview" id="cdHomeOverview">
<div className="para-box">
<p>
                            The <strong>Schema Doc Generator</strong> agent converts raw data configurations into
                            human-readable data dictionaries for system architecture clarity.
                        </p>
<div className="image-wrapper">
<img alt="Schema Doc Generator" className="demo-img" src="/assets/images/think-agent/schema-doc-generator-1.png"/>
</div>
<div className="para-box">
<h3 className="h3">
                                Core Mechanics
                            </h3>
<ul className="cd-overview-ul">
<li>
<strong>
                                        Object Scoping:
                                    </strong>
<span>
                                        Targets specific data structures, schemas, or tables across your system
                                        workspace, pre-selecting all components by default for a complete project
                                        dictionary.
                                    </span>
</li>
<li>
<strong>
                                        Pre-Execution Planning:
                                    </strong>
<span>
                                        Outlines a quick structure of the chosen schemas and stalls for explicit user
                                        approval before launching the doc generation engine.
                                    </span>
</li>
<li>
<strong>
                                        Semantic Content Generation:
                                    </strong>
<span>
                                        Analyzes code paths to automatically write a clear functional purpose and
                                        comprehensive field-by-field notes for each target object.
                                    </span>
</li>
<li>
<strong>
                                        Data Dictionary Output:
                                    </strong>
<span>
                                        Assembles structural metrics into a clean, well-formatted reference index ready
                                        for engineering team onboarding or compliance auditing.
                                    </span>
</li>
</ul>
</div>
<div className="para-box">
<h3 className="h3">
                                Step by Step Guide
                            </h3>
<h4 style={{marginTop: '20px'}} className="h4">
                                Step 1: Select Objects to Index
                            </h4>
<p>
                                Review your active project directory. Keep all data objects selected to maintain a
                                centralized system reference, or uncheck specific tables to isolate a particular
                                database schema or module.
                            </p>
<div className="image-wrapper">
<img alt="Schema Doc Generator" className="demo-img" src="/assets/images/think-agent/schema-doc-generator-2.png"/>
</div>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 2: Review and Authorize the Documentation Plan
                            </h4>
<p>
                                Examine the initial summary outline generated by the agent. This step verifies the
                                targeted boundaries and definitions to be parsed. Give your go-ahead to authorize the
                                extraction routine.
                            </p>
<div className="image-wrapper">
<img alt="Schema Doc Generator" className="demo-img" src="/assets/images/think-agent/schema-doc-generator-3.png"/>
</div>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 3: Run the Schema Parsing Engine
                            </h4>
<p>
                                Allow the agent to scan your system architecture models. The engine reviews data types,
                                references, nullable flags, and internal relationships to synthesize technical
                                parameters into plain-language definitions.
                            </p>
<div className="image-wrapper">
<img alt="Schema Doc Generator" className="demo-img" src="/assets/images/think-agent/schema-doc-generator-4.png"/>
</div>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 4: Access Your Data Dictionary
                            </h4>
<p>
                                Open the finalized documentation file. Review the generated operational purposes and
                                detailed field notes to align technical and non-technical stakeholders on system data
                                models.
                            </p>
<div className="image-wrapper">
<img alt="Schema Doc Generator" className="demo-img" src="/assets/images/think-agent/schema-doc-generator-5.png"/>
</div>
</div>
</div>
</section>
</main>
    </div>
  );
};

export default DesignerAgentSchemaDocGenerator;
