import React from "react";

const DesignerAgentCrmDataQualityAuditor = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>CRM Data Quality Auditor</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>CRM Data Quality Auditor</strong> agent analyzes your
              Customer Relationship Management database structure to identify
              duplicates, formatting anomalies, missing fields, and stale client
              records without risking production data integrity.
            </p>
            <div>
              <img
                alt="CRM Data Quality Auditor"
                src="/assets/images/think-agent/CRM-data-quality-auditor-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Schema-Driven Analysis:</strong>
                  <span>
                    Maps directly onto your live database tables (such as
                    Accounts, Contacts, Leads, or Opportunities) to audit your
                    exact data architecture rather than relying on generic
                    assumptions.
                  </span>
                </li>
                <li>
                  <strong>Prioritized Audit Planning:</strong>
                  <span>
                    Outlines an initial evaluation blueprint focusing on
                    high-value business entities and critical verification rules
                    (e.g., email syntax, phone formatting, or orphan records)
                    and pauses for your approval.
                  </span>
                </li>
                <li>
                  <strong>Protected Profile Execution:</strong>
                  <span>
                    Deploys safe, read-only analytical queries capped with
                    resource boundaries to profile records without altering any
                    existing CRM data.
                  </span>
                </li>
                <li>
                  <strong>Data Health &amp; Remediation Report:</strong>
                  <span>
                    Compiles a comprehensive health scorecard highlighting
                    duplicate records, unformatted data strings, and empty
                    fields alongside exact SQL or structural remediation fixes.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Select CRM Entities to Audit</h4>
              <p>
                Review your connected database tables. The agent defaults to
                evaluating your entire active CRM workspace, but you can narrow
                the scope to isolate specific target entities like your leads
                funnel or contacts registry.
              </p>
              <div>
                <img
                  alt="CRM Data Quality Auditor"
                  src="/assets/images/think-agent/CRM-data-quality-auditor-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Review and Authorize the Quality Blueprint</h4>
              <p>
                Examine the preliminary profiling plan generated by the agent.
                This step lists the exact validation rules, deduplication
                parameters, and target schemas that will be analyzed. Confirm
                the plan to launch the data sweep.
              </p>
              <div>
                <img
                  alt="CRM Data Quality Auditor"
                  src="/assets/images/think-agent/CRM-data-quality-auditor-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Non-Invasive Profiling Engine</h4>
              <p>
                Allow the agent to scan your data profiles. The system executes
                optimized, read-only scripts to measure record completeness,
                detect duplicate patterns (such as matching email domains or
                close-match names), and check for stale touchpoints.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Access the Health Scorecard and Fixes</h4>
              <p>Open the final data quality dashboard to clean your system:</p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Issue Classification:</strong> Review flagged entries
                  grouped by type: Duplicates, Gaps (empty required fields),
                  Format Issues (corrupted telephone or country codes), and
                  Stale Records.
                </li>
                <li>
                  <strong>Remediation Scripts:</strong> Copy the provided
                  data-cleansing scripts or merge logic directly into your data
                  pipeline to update incomplete entries and deduplicate your
                  records safely.
                </li>
              </ul>
              <div>
                <img
                  alt="CRM Data Quality Auditor"
                  src="/assets/images/think-agent/CRM-data-quality-auditor-4.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentCrmDataQualityAuditor;
