import React from "react";

const DesignerAgentTestGapFinder = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Test Gap Finder</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Test Gap Finder</strong> agent maps your test coverage
              onto critical business flows to identify blind spots in your
              validation suite.
            </p>
            <div>
              <img
                alt="Test Gap Finder"
                src="/assets/images/think-agent/test-gap-finder-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Business Flow Alignment:</strong>
                  <span>
                    Maps existing test suites directly to core operational and
                    business logic flows rather than raw lines of code.
                  </span>
                </li>
                <li>
                  <strong>Dual-Scope Selection:</strong>
                  <span>
                    Targets specific business flows and corresponding test files
                    concurrently, pre-selecting all assets by default for an
                    exhaustive evaluation.
                  </span>
                </li>
                <li>
                  <strong>Cross-Reference Analysis:</strong>
                  <span>
                    Parses each designated business flow against existing test
                    cases to isolate unvalidated paths, conditions, or missing
                    assertions.
                  </span>
                </li>
                <li>
                  <strong>Gap Telemetry &amp; Recommendations:</strong>
                  <span>
                    Generates a targeted breakdown of coverage percentages per
                    business flow alongside automated recommendations for
                    missing test scripts.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Select Flows and Test Suites</h4>
              <p>
                Review your project workspace to select the specific business
                flows and test files you want to audit. Keep all items checked
                by default to execute a comprehensive, platform-wide gap
                analysis.
              </p>
              <div>
                <img
                  alt="Select Flows and Test Suites"
                  src="/assets/images/think-agent/test-gap-finder-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Verify the Analysis Plan</h4>
              <p>
                Examine the preliminary blueprint generated by the agent. This
                step outlines how your test scripts will be mapped against your
                business logic models. Click confirm to authorize the tracking
                sequence.
              </p>
              <div>
                <img
                  alt="Verify Analysis Plan"
                  src="/assets/images/think-agent/test-gap-finder-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Verification Engine</h4>
              <p>
                Allow the agent to process your files. The engine traces every
                operational node within your business flows, cross-referencing
                them with your existing test assertions to identify functional
                holes.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Review Flow Coverage and Deploy Suggested Tests</h4>
              <p>
                Open the final telemetry report to evaluate your testing health:
              </p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Coverage per Flow:</strong> Review the explicit
                  coverage percentage assigned to each critical business path to
                  prioritize your testing efforts.
                </li>
                <li>
                  <strong>Suggested Tests:</strong> Use the automatically
                  generated test case blueprints to write missing scripts,
                  closing critical validation gaps before deployment.
                </li>
              </ul>
              <div>
                <img
                  alt="Review Coverage &amp; Suggested Tests"
                  src="/assets/images/think-agent/test-gap-finder-4.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentTestGapFinder;
