import React from "react";

const DesignerAgentSecurityAnalyst = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Security Analyst</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Security Analyst</strong> agent provides an automated
              application-security review of your source code to uncover hidden
              vulnerabilities, exposed secrets, and infrastructure
              misconfigurations.
            </p>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Custom Scan Scoping:</strong>
                  <span>
                    Audits targeted files and directories throughout your
                    repository, with all assets pre-selected by default to
                    ensure complete security coverage.
                  </span>
                </li>
                <li>
                  <strong>Pre-Execution Planning:</strong>
                  <span>
                    Outlines a structured review strategy for your evaluation
                    and confirmation before kicking off the primary analysis
                    engine.
                  </span>
                </li>
                <li>
                  <strong>Multi-Vector Vulnerability Inspection:</strong>
                  <span>
                    Examines every selected file against multiple threat
                    vectors, scanning concurrently for software vulnerabilities,
                    hardcoded secrets, and structural misconfigurations.
                  </span>
                </li>
                <li>
                  <strong>Prioritized Action Items:</strong>
                  <span>
                    Compiles a severity-graded report that categorizes
                    discoveries by risk level and provides concrete, executable
                    code fixes.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step-by-Step Guide</h3>
              <h4>Step 1: Configure Your Scan Scope</h4>
              <p>
                Inspect your repository directory structure. Keep all files and
                folders selected for a baseline comprehensive audit, or uncheck
                specific directories to isolate particular modules or
                microservices.
              </p>
              <div>
                <img
                  alt="Security Analyst"
                  src="/assets/images/think-agent/security-analyst-1.png"
                />
              </div>
              <div>
                <img
                  alt="Security Analyst"
                  src="/assets/images/think-agent/security-analyst-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Review and Confirm the Analysis Plan</h4>
              <p>
                Examine the scan blueprint generated by the agent. Review the
                targeted boundaries and click confirm to authorize the
                application-security evaluation.
              </p>
              <div>
                <img
                  alt="Security Analyst"
                  src="/assets/images/think-agent/security-analyst-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Execute the Multi-Vector Audit</h4>
              <p>
                Allow the agent to parse your source files. The analysis engine
                will scan your code paths to flag logic flaws, authentication
                vulnerabilities, exposed tokens, and configuration mistakes.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Remediate the Findings</h4>
              <p>
                Open the final security report and sort the issues by their
                severity grades (e.g., Critical, High, Medium, Low). Use the
                provided concrete code fixes to directly patch vulnerabilities,
                rotate exposed credentials, and correct infrastructure-as-code
                misconfigurations.
              </p>
              <div>
                <img
                  alt="Security Analyst"
                  src="/assets/images/think-agent/security-analyst-4.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentSecurityAnalyst;
