import React from "react";

const DesignerAgentSqlExplorer = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>SQL Explorer</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>SQL Explorer</strong> agent translates plain English
              questions into safe, read-only database queries to retrieve
              instant data insights without requiring manual code composition.
            </p>
            <div>
              <img
                alt="SQL Explorer"
                src="/assets/images/think-agent/SQL-explorer-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Natural Language Translation:</strong>
                  <span>
                    Interprets structural data questions written in plain
                    English and translates them into execution-ready database
                    queries.
                  </span>
                </li>
                <li>
                  <strong>Guaranteed Safe Execution:</strong>
                  <span>
                    Configured strictly to generate and execute safe, read-only
                    SELECT statements against your database schema, preventing
                    unauthorized data modification or structural deletion.
                  </span>
                </li>
                <li>
                  <strong>Automatic Resource Protection:</strong>
                  <span>
                    Automatically caps every generated query with a hard
                    resource LIMIT boundary to prevent query performance
                    degradation and massive data over-fetching.
                  </span>
                </li>
                <li>
                  <strong>Transparent Verification:</strong>
                  <span>
                    Delivers raw structural query results alongside the
                    transparent, underlying SQL statement generated by the AI
                    for engineering audit and verification.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Submit Your Plain English Question</h4>
              <p>
                Navigate to the query input workspace and type out your data
                question using normal prose. Focus on specifying the targets and
                conditions you want to measure{" "}
                <em>
                  (e.g., "Show me the total number of new user registrations
                  from last week grouped by country")
                </em>
                .
              </p>
              <div>
                <img
                  alt="SQL Explorer"
                  src="/assets/images/think-agent/SQL-explorer-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Schema Assessment and Query Building</h4>
              <p>
                Allow the agent to map your English text onto your active
                database schema definitions. The underlying compiler
                automatically crafts an optimized, read-only SELECT query
                matching your logic.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Protected Query</h4>
              <p>
                The agent triggers the execution cycle directly against your
                target database workspace. The platform applies a strict LIMIT
                clause to your query behind the scenes to keep data parsing
                performant and secure.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Evaluate Results and Generated Code</h4>
              <p>
                Review the final output dashboard which splits your data into
                two clean blocks:
              </p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Results Table:</strong> Inspect the structured rows
                  and columns returned by your data question.
                </li>
                <li>
                  <strong>Generated SQL:</strong> Review the exact source query
                  written by the AI engine, allowing you to copy, study, or save
                  the statement for future engineering tasks.
                </li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentSqlExplorer;
