import React from "react";

const DesignerAgentCodeReviewer = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Code Reviewer</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Code Reviewer</strong> agent conducts a
              principal-engineer-level review of your source code to evaluate
              structural integrity, logic, and code health.
            </p>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Custom Scope Selection:</strong>
                  <span>
                    Assesses targeted files throughout your repository, with all
                    codebase assets pre-selected by default to ensure an
                    exhaustive engineering evaluation.
                  </span>
                </li>
                <li>
                  <strong>Review Plan Confirmation:</strong>
                  <span>
                    Stages a preliminary blueprint of the files to be checked,
                    allowing you to review the scope before initiating the
                    deeper analysis.
                  </span>
                </li>
                <li>
                  <strong>Comprehensive Code Evaluation:</strong>
                  <span>
                    Analyzes each file concurrently for software bugs,
                    structural readability issues, syntax errors, performance
                    bottlenecks, and design pattern anti-patterns.
                  </span>
                </li>
                <li>
                  <strong>Graded Engineering Verdict:</strong>
                  <span>
                    Delivers an actionable report complete with categorized
                    findings, direct code fixes, and an overall architectural
                    quality verdict.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Scope Your Engineering Review</h4>
              <div>
                <img
                  alt="Scope Review"
                  src="/assets/images/think-agent/code-reviewer-1.png"
                />
              </div>
              <p>
                Navigate your project directory and choose the files you want to
                audit. Keep all files selected to execute a comprehensive
                baseline review, or refine the selection to target specific
                modified scripts or newly added modules.
              </p>
              <div>
                <img
                  alt="Select Files"
                  src="/assets/images/think-agent/code-reviewer-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Verify the Review Scope</h4>
              <p>
                Inspect the summary review plan generated by the agent. This
                confirms the file boundaries and indexing pathways. Click Run
                Scan to confirm and launch the engineering analysis.
              </p>
              <div>
                <img
                  alt="Verify Scope"
                  src="/assets/images/think-agent/code-reviewer-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Analysis Engine</h4>
              <p>
                Allow the agent to parse your code structures. The engine reads
                through the codebase, checking logic flows, tracking variable
                lifecycles, and identifying deviations from engineering best
                practices.
              </p>
              <div>
                <img
                  alt="Analysis Engine"
                  src="/assets/images/think-agent/code-reviewer-4.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 4: Implement Fixes and Check the Verdict</h4>
              <p>
                Open the final code review report. Prioritize your refactoring
                based on the graded findings, apply the recommended inline code
                fixes, and review the principal engineer's final verdict to
                determine if the code meets your production standards.
              </p>
              <div>
                <img
                  alt="Implement Fixes"
                  src="/assets/images/think-agent/code-reviewer-5.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentCodeReviewer;
