import React from "react";

const DesignerAgentApiDocGenerator = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>API Doc Generator</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>API Doc Generator</strong> agent parses source code
              files to automatically generate structured API reference
              documentation and usage examples.
            </p>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Endpoint Scoping:</strong>
                  <span>
                    Audits selected route, controller, or request handler files
                    across your project directory, pre-selecting all files by
                    default for a complete API map.
                  </span>
                </li>
                <li>
                  <strong>Documentation Planning:</strong>
                  <span>
                    Generates a preliminary structural blueprint of the
                    endpoints to be documented for confirmation before running
                    the parser.
                  </span>
                </li>
                <li>
                  <strong>Deep File Parsing:</strong>
                  <span>
                    Inspects each file to extract active endpoints, HTTP
                    methods, URI parameters, request bodies, and expected status
                    responses.
                  </span>
                </li>
                <li>
                  <strong>Structured Reference Output:</strong>
                  <span>
                    Publishes an organized, interactive API reference manual
                    complete with request/response schema examples.
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide:</h3>
              <h4>Step 1: Select Your API Source Files</h4>
              <div>
                <img
                  alt="API Doc Generator"
                  src="/assets/images/think-agent/api-doc-generator-1.png"
                />
              </div>
              <p>
                Review your project folder structure. Select the relevant route
                files, controllers, or endpoint handlers that define your
                application's entry points. Leave all options selected by
                default to ensure no endpoints are missed.
              </p>
              <div>
                <img
                  alt="API Doc Generator"
                  src="/assets/images/think-agent/api-doc-generator-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Approve the Documentation Plan</h4>
              <p>
                Review the quick summary plan generated by the agent. This
                layout verifies which modules and routing files will be indexed.
                Confirm the plan to start the extraction process.
              </p>
              <div>
                <img
                  alt="API Doc Generator"
                  src="/assets/images/think-agent/api-doc-generator-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Run the Schema Extraction Engine</h4>
              <p>
                Allow the generator to index your code. The engine reads through
                your code handlers, identifying the exact parameter types,
                validation rules, query strings, and payload signatures.
              </p>
              <div>
                <img
                  alt="API Doc Generator"
                  src="/assets/images/think-agent/api-doc-generator-4.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 4: Utilize the Structured Reference</h4>
              <p>
                Access the newly compiled documentation. You can now use the
                structured reference tables and boilerplate payload examples to
                update integration setups, share with frontend developers, or
                export to external API management platforms.
              </p>
              <div>
                <img
                  alt="API Doc Generator"
                  src="/assets/images/think-agent/api-doc-generator-5.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentApiDocGenerator;
