import React from "react";

const DesignerAgentResumeScreener = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Resume Screener</h1>
        <section>
          <div className="para-box">
            <p>
              The <strong>Resume Screener</strong> agent provides a systematic,
              evidence-based evaluation of job applicants by scoring candidate
              backgrounds directly against your explicit role requirements to
              build an objective talent pipeline.
            </p>
            <div>
              <img
                alt="Resume Screener"
                src="/assets/images/think-agent/resume-screener-1.png"
              />
            </div>
            <div className="para-box">
              <h3>Core Mechanics</h3>
              <ul>
                <li>
                  <strong>Batch Candidate Parsing:</strong>
                  <span>
                    Accepts multiple resume profiles simultaneously in a single
                    text field, using a simple delimiter (---) to cleanly
                    isolate individual candidate data.
                  </span>
                </li>
                <li>
                  <strong>Pre-Screening Alignment:</strong>
                  <span>
                    Reviews your target job description and draft evaluation
                    criteria, pausing for explicit confirmation before
                    processing candidate information.
                  </span>
                </li>
                <li>
                  <strong>Must-Have Criteria Scoring:</strong>
                  <span>
                    Measures each candidate's professional history against your
                    critical prerequisites (such as specific technology stacks,
                    certifications, or operational experience).
                  </span>
                </li>
                <li>
                  <strong>Ranked Candidate Shortlist:</strong>
                  <span>
                    Compiles evaluations into a structured, performance-ranked
                    leaderboard detailing individual strengths, missing skill
                    gaps, and a clear screening verdict (e.g., Proceed, Hold, or
                    Decline).
                  </span>
                </li>
              </ul>
            </div>
            <div className="para-box">
              <h3>Step by Step Guide</h3>
              <h4>Step 1: Input Candidate Resumes</h4>
              <p>
                Paste your candidate resumes into the text submission workspace.
                When uploading multiple applicants at once, separate each
                profile by inserting a three-dash horizontal rule (---) on its
                own line between them.
              </p>
              <div>
                <img
                  alt="Resume Screener"
                  src="/assets/images/think-agent/resume-screener-2.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 2: Establish and Confirm Evaluation Criteria</h4>
              <p>
                Review the initial screening plan generated by the agent based
                on your target role requirements. Adjust the "must-have"
                parameters or experience baselines as needed, then confirm the
                plan to initiate the evaluation.
              </p>
              <div>
                <img
                  alt="Resume Screener"
                  src="/assets/images/think-agent/resume-screener-3.png"
                />
              </div>
            </div>
            <div className="para-box">
              <h4>Step 3: Execute the Screening Sweep</h4>
              <p>
                Allow the agent to audit the applicant pool. The engine parses
                the professional history, education blocks, and core
                competencies of each candidate, checking for verifiable evidence
                of your required criteria while eliminating subjective bias.
              </p>
            </div>
            <div className="para-box">
              <h4>Step 4: Analyze the Ranked Shortlist</h4>
              <p>
                Open the finalized screening board to make your hiring
                decisions:
              </p>
              <ul style={{ marginTop: "10px", marginBottom: "20px" }}>
                <li>
                  <strong>Ranked Leaderboard:</strong> View applicants ordered
                  by their criteria match scores to immediately identify
                  top-tier talent.
                </li>
                <li>
                  <strong>Strengths &amp; Gaps:</strong> Review the clear
                  breakdowns of where candidates excel and where their
                  experience falls short.
                </li>
                <li>
                  <strong>Actionable Verdicts:</strong> Use the automated hiring
                  verdicts to quickly coordinate interviews or update candidate
                  tracking statuses.
                </li>
              </ul>
              <div>
                <img
                  alt="Resume Screener"
                  src="/assets/images/think-agent/resume-screener-4.png"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default DesignerAgentResumeScreener;
