import React from 'react';

const DesignerAgentSecretScanner = () => {
  return (
    <div className="doc-page-content">
      <main className="cd-main-content" id="cd-main">
<h1 className="cd-page-title" id="cdHomeTitle">
                    Secret Scanner
                </h1>
<section className="cd-overview" id="cdHomeOverview">
<div className="para-box">
<p>
                            The <strong>Secret Scanner</strong> agent systematically hunts for hardcoded secrets,
                            cryptographic keys, tokens, and credentials embedded across project source codes and config
                            files.
                        </p>
<div className="para-box">
<h3 className="h3">
                                Core Mechanics
                            </h3>
<ul className="cd-overview-ul">
<li>
<strong>
                                        Targeted Sweeping:
                                    </strong>
<span>
                                        Scans selected files and folders across your repository workspace, utilizing
                                        global selections by default for uniform coverage.
                                    </span>
</li>
<li>
<strong>
                                        Scan Strategy Confirmation:
                                    </strong>
<span>
                                        Outlines a brief execution plan for review before initiating deep file parsing.
                                    </span>
</li>
<li>
<strong>
                                        Automated Credential Extraction:
                                    </strong>
<span>
                                        Discovers high-risk artifacts including API keys, bearer tokens, passwords, and
                                        private certificates hidden in code text.
                                    </span>
</li>
<li>
<strong>
                                        Risk Grading &amp; Remediation:
                                    </strong>
<span>
                                        Generates a prioritized, graded results report specifying which exposed secrets
                                        must be rotated immediately or completely removed.
                                    </span>
</li>
</ul>
</div>
<div className="para-box">
<h3 className="h3">
                                Step-by-Step Guide
                            </h3>
<h4 style={{marginTop: '20px'}} className="h4">
                                Step 1: Define the Scan Targets
                            </h4>
<p>
                                Review the repository directory layout. By default, all files and folders are
                                pre-selected to prevent hidden credentials
                                from being missed. Use individual checkboxes or folder paths to exclude non-production
                                code if necessary.
                            </p>
<div className="image-wrapper">
<img alt="Secret Scanner" className="demo-img" src="/assets/images/think-agent/secret-scanner-1.png"/>
</div>
<div className="image-wrapper">
<img alt="Secret Scanner" className="demo-img" src="/assets/images/think-agent/secret-scanner-2.png"/>
</div>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 2: Confirm the Scan Plan
                            </h4>
<p>
                                Review the brief scan summary generated by the platform. This confirmation step outlines
                                the exact file boundaries and
                                performance expectations before processing begins.
                            </p>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 3: Trigger the Secrets Hunt
                            </h4>
<p>
                                Click the initiation button to run the automated parser. The agent will inspect each
                                targeted asset, searching for
                                explicit patterns, high-entropy strings, and known credential formats.
                            </p>
<div className="image-wrapper">
<img alt="Secret Scanner" className="demo-img" src="/assets/images/think-agent/secret-scanner-3.png"/>
</div>
</div>
<div className="para-box">
<h4 className="h4">
                                Step 4: Act on the Graded Report
                            </h4>
<p>
                                Examine the final output list organized by severity grading. Identify the critical
                                exposures and execute the required
                                security responses:
                            </p>
<div className="image-wrapper">
<img alt="Secret Scanner" className="demo-img" src="/assets/images/think-agent/secret-scanner-4.png"/>
</div>
</div>
</div>
</section>
</main>
    </div>
  );
};

export default DesignerAgentSecretScanner;
