import React from "react";

const PortalUsageAndAnalysis = () => {
  return (
    <div className="doc-page-content">
      <main>
        <h1>Usage &amp; Analysis</h1>

        <section>
          <p>
            The Usage &amp; Analytics section provides a detailed breakdown of
            your platform utilization, token consumption, and transactional
            metrics. This screen helps you audit costs and understand exactly
            how your AI agents are consuming system resources.
          </p>
          <div className="content-box">
            <div>
              <img
                alt="Usage &amp; Analysis"
                src="/assets/images/portal/03-usage-analysis.png"
              />
            </div>
            <h3>Sub-Tab Navigation Bar</h3>
            <p>
              Located at the top of the workspace, these tabs allow you to
              toggle between different analytical views:
            </p>
            <ul>
              <li>
                <strong>Overview (Current View):</strong>
                <span>
                  A high-level dashboard summarizing volume metrics and overall
                  token balances.
                </span>
              </li>
              <li>
                <strong>By Model:</strong>
                <span>
                  Breaks down consumption data based on the specific AI model
                  engines processing your requests.
                </span>
              </li>
              <li>
                <strong>By Model:</strong>
                <span>
                  Breaks down consumption data based on the specific AI model
                  engines processing your requests.
                </span>
              </li>
              <li>
                <strong>Cost Breakdown:</strong>
                <span>
                  Translates token usage into actual financial expenditures
                  based on your billing tier.
                </span>
              </li>
              <li>
                <strong>Projects:</strong>
                <span>
                  Segregates usage metrics by individual active workspaces or
                  development branches.
                </span>
              </li>
            </ul>
            <h3>High-Level Summary Cards</h3>
            <p>
              This interactive data table itemizes execution metrics segmented
              by individual development environments inside the selected
              tracking window:
            </p>
            <h3>Daily Usage Time-Series Chart</h3>
            <p>
              The top metrics section highlights cumulative totals for quick
              monitoring:
            </p>
            <ul>
              <li>
                <strong>Total Requests:</strong>
                <span>
                  The aggregate number of execution calls or tasks initiated
                  across your pipelines (e.g., 797 requests).
                </span>
              </li>
              <li>
                <strong>Total Tokens:</strong>
                <span>
                  The combined volume of processing units used by the system
                  (e.g., 19.5M tokens). This includes input, output, and cached
                  context.
                </span>
              </li>
              <li>
                <strong>Prompt Tokens:</strong>
                <span>
                  The standalone volume of input data sent to the models (e.g.,
                  18.3M tokens), indicating the heavy baseline processing of
                  instructions, documentation, and system state rules.
                </span>
              </li>
            </ul>
            <h3>Token Breakdown Module</h3>
            <p>
              This card explicitly itemizes how your total tokens are
              distributed during execution loops:
            </p>
            <table className="config-table">
              <thead>
                <tr>
                  <th>Token Type</th>
                  <th>Metric Volume</th>
                  <th>Functional Purpose</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Prompt tokens</td>
                  <td>18.3M</td>
                  <td>
                    Represents the raw input instructions, system architectures,
                    and engineering requirements parsed by the AI models.
                  </td>
                </tr>
                <tr>
                  <td>Completion tokens</td>
                  <td>1.2M</td>
                  <td>
                    Represents the actual output generated by your AI agents
                    (e.g., code, generated text, or processed system steps).
                  </td>
                </tr>
                <tr>
                  <td>Cache read tokens</td>
                  <td>10.9M</td>
                  <td>
                    Represents previously processed context that was
                    successfully retrieved from memory. High values here mean
                    the system is optimizing efficiency and saving costs by
                    avoiding redundant processing.
                  </td>
                </tr>
                <tr>
                  <td>Cache write tokens</td>
                  <td>381.6K</td>
                  <td>
                    Tracks new, reusable contextual data written into the
                    platform's cache infrastructure to accelerate subsequent
                    agent tasks.
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </div>
  );
};

export default PortalUsageAndAnalysis;
